### ISSUE TITLE
[BUG] Using Plugins gives error

### ISSUE THREAD

**Issue by btotharye** [cardoso/errbot-rocketchat#3]
Anytime I try to install or use plugins then in the logs I start noticing the following:

```
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ws4py-0.4.2-py3.5.egg/ws4py/websocket.py", line 524, in run
    if not self.once():
  File "/usr/local/lib/python3.5/dist-packages/python_ddp-0.1.5-py3.5.egg/DDPClient.py", line 53, in once
    return super(DDPSocket, self).once()
  File "/usr/local/lib/python3.5/dist-packages/ws4py-0.4.2-py3.5.egg/ws4py/websocket.py", line 406, in once
    if not self.process(self.buf):
  File "/usr/local/lib/python3.5/dist-packages/ws4py-0.4.2-py3.5.egg/ws4py/websocket.py", line 476, in process
    self.received_message(s.message)
  File "/usr/local/lib/python3.5/dist-packages/python_ddp-0.1.5-py3.5.egg/DDPClient.py", line 41, in received_message
    self.emit('received_message', data)
  File "/usr/local/lib/python3.5/dist-packages/pyee-3.0.3-py3.5.egg/pyee/__init__.py", line 148, in emit
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/python_ddp-0.1.5-py3.5.egg/DDPClient.py", line 216, in received_message
    callback(data.get('error'), sub_id)
  File "/usr/local/lib/python3.5/dist-packages/python_meteor-0.1.6-py3.5.egg/MeteorClient.py", line 210, in subscribed
    callback(None)
  File "/home/bhopkins/errbot-rocketchat/src/aoikrocketchaterrbot/backends/aoikrocketchaterrbot.py", line 986, in _meteor_subscribe_callback
    self.connect_callback()
  File "/usr/local/lib/python3.5/dist-packages/errbot-5.1.3-py3.5.egg/errbot/core.py", line 648, in connect_callback
    self.warn_admins(errors)
  File "/usr/local/lib/python3.5/dist-packages/errbot-5.1.3-py3.5.egg/errbot/core.py", line 579, in warn_admins
    self.send(self.build_identifier(admin), warning)
  File "/home/bhopkins/errbot-rocketchat/src/aoikrocketchaterrbot/backends/aoikrocketchaterrbot.py", line 1289, in send
    raise ValueError(error_msg)
ValueError: Argument `in_reply_to` must be given.
```

It seems like maybe there is an issue with how the send is setup.  The discord backend that currently works for example is https://github.com/gbin/err-backend-discord for a reference which I helped get going recently.  I haven't looked over it all yet but was hoping you might know the issue versus me having to look over this code and familiarize myself with it.

thanks

**Comment by btotharye** [comment]
just verified get same error on errbot 4.3.4 as well.  Rocket chat version is 0.59.3

**Comment by cardoso** [comment]
Hi @btotharye, thanks for reporting this! 👍 

I've noticed and fixed some issues with breaking changes in the errbot front-end before, this might be another one.

I'll try and take a look this weekend. Probably an easy fix.

**Comment by btotharye** [comment]
thanks I'll try to see if I can figure it out as well but thought you might be more familiar with it.

**Comment by cardoso** [comment]
Feel free to take a look and submit a PR if it's ok. Thanks!!

By the way,

![](https://i.imgur.com/RGEULM3.png)

I just tried installing a plugin here and it worked 🤔 no bad logs

**Comment by btotharye** [comment]
interesting that one works for me as well

**Comment by btotharye** [comment]
got it working for now, seems like it was cause of a missing package requirement on my end, its now working in rocket chat.

thanks
